version: '2'
services:
    v7gtw-app:
        image: v7gtw
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://v7gtw-mysql:3306/v7gtw?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    v7gtw-mysql:
        extends:
            file: mysql.yml
            service: v7gtw-mysql
