version: '2'
services:
    v7gtw-mysql:
        image: mysql:5.7.20
        # volumes:
        #     - ~/volumes/jhipster/v7gtw/mysql/:/var/lib/mysql/
        environment:
            - MYSQL_USER=root
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_DATABASE=v7gtw
        ports:
            - 3306:3306
        command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8mb4 --explicit_defaults_for_timestamp
